services:
  frontend:
    build:
      context: .
      target: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: wget -q --spider http://localhost:5000/health || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  test:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
      - ./playwright.config.js:/app/playwright.config.js
    command: npm test
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    profiles:
      - test
